name: flutter_dot_json_env
description: "Easily configure any flutter application with global variables using a `local.json` file."
version: 1.0.1
homepage: https://github.com/govarthananve/flutter_dot_json_env

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
